db:
    username: "serj"
    host: "192.168.52.129"
    port: "5432"
    name: "serjdb"
    sslmode: "require"

db_tables:
    users_table: "users"
    tasks_table: "tasks"
    labels_table: "labels"
    tasks_labels_table: "tasks_labels"